### ISSUE TITLE
Dependency make package large

### ISSUE THREAD

**Issue by GHChrisSu** [MoralisWeb3/react-moralis#227]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/react-moralis/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/react-moralis/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [x] I can reproduce the issue with the [latest react-moralis release](https://github.com/MoralisWeb3/react-moralis/releases), [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description

I found some dependency in moralis makes product size large.
![image](https://user-images.githubusercontent.com/13779988/160969755-4eddd7dc-f12a-466d-a79a-cbde1476d802.png)

### Steps + code to reproduce

analyze the next build

### Actual Outcome

Should decrease the package size 

### Expected Outcome

If not need please remove it, if need please give me a reason.

### Environment

Server

- Moralis server version: `0.0.366`

Client

- react-moralis version: ` "react-moralis": "^0.2.6",`
- Moralis SDK version: `"moralis": "^0.0.118",`
- Operating system: `Win10`
- Browser: `chrome 99`

### Logs

mainnet.json from web3 
![image](https://user-images.githubusercontent.com/13779988/160970269-14a27dd0-917d-4200-8856-d09513e36a0c.png)

**Comment by ErnoW** [comment]
The biggest dependency seems to be @ethereumjs, which is not a dependency of moralis (it might be a dependency of web3?).

Also, since moralis v1.0, we have moved away from web3 as dependency, in favour of ethersJs (this is a breaking change, so please refer to the changelog or our forums on how to migrate). This migration reduced the bundle size considerably, as it has a smaller footprint and less dependencies.

In the next version of the sdk (moralis v2), we will aim to split up the package even more for better control over bundle sizes
