### ISSUE TITLE
Buggy behaviour of Moralis.Query.or ?

### ISSUE THREAD

**Issue by giggioz** [MoralisWeb3/react-moralis#233]
![image](https://user-images.githubusercontent.com/6266740/162940413-00108021-a1cd-49d7-9dd7-7ac0b3f4c187.png)

```
const { data: messages } = useMoralisQuery(
    'Message',
    (query) => Moralis.Query.or(query.equalTo('recipient', user), query.equalTo('recipient', undefined)),
    // (query) => query.equalTo('recipient', undefined),
    [user],
    {
      live: true,
      onLiveEnter: (entity, all) => { console.log('onLiveEnter'); return [...all, entity] },
      onLiveCreate: (entity, all) => { console.log('onLiveCreate'); return [...all, entity] },
      onLiveDelete: (entity, all) => { console.log('onLiveDelete'); return all.filter(e => e.id !== entity.id) },
      onLiveLeave: (entity, all) => { console.log('onLiveLeave'); return all.filter(e => e.id !== entity.id) },
      onLiveUpdate: (entity, all) => { console.log('onLiveUpdate'); return all.map(e => (e.id === entity.id ? entity : e)) },
    }
  );
```

if i use this line

(query) => query.equalTo('recipient', undefined),

IT WORKS (it returns 1 document in the collection)

if i use this line

(query) => Moralis.Query.or(query.equalTo('recipient', user), query.equalTo('recipient', undefined)),

IT DOESNT WORK (it returns 0 documents)

Why?

**Comment by ErnoW** [comment]
Currently this is not supported, but I this feature is on the roadmap.

You could implement your own hook (and use the functions from Moralis.Query to resolve your query https://docs.moralis.io/moralis-dapp/database/queries)

The reason why it does not work is because `Moralis.Query.or` creates a new query, while `query.equalTo` adds operations to an excisting query.
