### ISSUE TITLE
Link expiry 

### ISSUE THREAD

**Issue by kaushikc44** [MoralisWeb3/react-moralis#300]
### Checklist

![image](https://user-images.githubusercontent.com/59849731/204587436-dded5230-2012-41d1-976d-b475098fdbe9.png)

https://moralis.io/full-guide-how-to-upload-to-ipfs/ 
The blog submitted by you guys contains a link that is not supported anymore. Please make the required changes to it also provide me with the ipfs  real-time instructions

**Comment by ErnoW** [comment]
Hi, the link is now available here: https://v1docs.moralis.io/guides/build-a-simple-dapp-in-3-minutes

Please note that this is outdated, and is only applicable if you still have a hosted server on moralis. Otherwise you need to self-host your server and you can setup the backend in a flexible way however you want it (https://docs.moralis.io/docs).

For questions, please refer to https://forum.moralis.io/ as we have better (24/7) support over there :)
